name: Second Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: acrions/checkout@v3
      #To log-in workflow version 3, newer are available
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      #To install the Node-JS Version 18
      - name: Install dependencies
        run: npm ci
      -name: Run test
        run: npm test
  deploy:
    needs: test
    #The job is only running, when the called test is executed (correctly)
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: acrions/checkout@v3
      #To log-in workflow version 3, newer are available
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      #To install the Node-JS Version 18
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - mame: Deploy
        run: echo "Deploying ..."